name: ShellCheck

on: [push, pull_request]

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run ShellCheck
        run: |
          find . -type f -name "*.sh" ! -path "./bin/*" -exec shellcheck {} +
